export const recipes = [
  {
    id: 1,
    title: "Classic Beef Wellington",
    slug: "classic-beef-wellington",
    difficulty: "Hard",
    prepTime: "45 mins",
    cookTime: "45 mins",
    servings: 6,
    author: "Chef Gordon",
    rating: 4.9,
    reviewCount: 342,
    badge: "Masterpiece",
    badgeColor: "bg-amber-500",
    description: "A show-stopping centerpiece featuring a perfectly cooked beef tenderloin coated in rich mushroom duxelles and prosciutto, all wrapped in crisp, golden puff pastry.",
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
    ingredients: [
      "1 center-cut beef tenderloin (2-3 lbs)",
      "2 tbsp olive oil",
      "2 tbsp Dijon mustard",
      "1 lb mixed mushrooms, finely chopped",
      "1 shallot, minced",
      "2 cloves garlic, minced",
      "1/2 cup dry white wine",
      "8-10 slices prosciutto",
      "1 package puff pastry, thawed",
      "2 egg yolks (for egg wash)",
      "Salt and freshly cracked black pepper"
    ],
    instructions: [
      "Season the beef tenderloin generously with salt and pepper. Sear in a hot skillet with olive oil until browned on all sides. Let cool, then brush all over with Dijon mustard.",
      "Make the duxelles: Sauté mushrooms, shallot, and garlic until moisture evaporates. Add wine and cook until dry. Season and let cool completely.",
      "Lay out plastic wrap, place prosciutto slices slightly overlapping. Spread duxelles evenly over the prosciutto.",
      "Place the beef on the prosciutto and roll it tightly using the plastic wrap. Twist the ends like a candy wrapper and chill for 30 minutes.",
      "Roll out the puff pastry, unwrap the beef, and place it in the center. Wrap the pastry around the beef, sealing the edges with egg wash. Brush the entire outside with egg wash.",
      "Bake at 400°F (200°C) for 35-45 minutes until the pastry is golden-brown and meat internal temperature reaches 130°F (54°C) for medium-rare.",
      "Rest for 15 minutes before carving."
    ]
  },
  {
    id: 2,
    title: "Slow Cooker Pot Roast",
    slug: "slow-cooker-pot-roast",
    difficulty: "Easy",
    prepTime: "20 mins",
    cookTime: "8 hours",
    servings: 8,
    author: "Home Kitchen",
    rating: 4.8,
    reviewCount: 890,
    badge: "Family Favorite",
    badgeColor: "bg-emerald-500",
    description: "The ultimate comfort food. This chuck roast slow-cooks all day until it completely melts in your mouth, swimming in a rich savory gravy with tender root vegetables.",
    image: "https://getinspiredeveryday.com/wp-content/uploads/2022/01/Slow-Cooker-Pot-Roast-Get-Inspired-Everyday-4.jpg",
    ingredients: [
      "3-4 lb beef chuck roast",
      "2 tbsp vegetable oil",
      "1 large onion, roughly chopped",
      "4 medium carrots, cut into chunks",
      "1 lb baby potatoes",
      "3 cloves garlic, smashed",
      "2 cups beef broth",
      "1/4 cup balsamic vinegar",
      "2 sprigs fresh rosemary",
      "2 sprigs fresh thyme",
      "Salt and black pepper"
    ],
    instructions: [
      "Season the chuck roast heavily with salt and pepper. Sear it in a hot skillet with oil until deeply browned on all sides (about 3-4 minutes per side).",
      "Place carrots, potatoes, onion, and garlic at the bottom of your slow cooker.",
      "Place the seared roast on top of the vegetables.",
      "Deglaze the skillet with balsamic vinegar and beef broth, scraping up brown bits. Pour this liquid over the roast.",
      "Add rosemary and thyme sprigs.",
      "Cover and cook on LOW for 8-9 hours or HIGH for 5-6 hours until the beef falls apart easily with a fork.",
      "Discard herb stems, shred beef slightly and serve hot with the vegetables and juices."
    ]
  },
  {
    id: 3,
    title: "Traditional Beef Bourguignon",
    slug: "traditional-beef-bourguignon",
    difficulty: "Medium",
    prepTime: "30 mins",
    cookTime: "3 hours",
    servings: 6,
    author: "Julia's Legacy",
    rating: 4.9,
    reviewCount: 512,
    badge: "Classic French",
    badgeColor: "bg-blue-500",
    description: "A rich, complex French stew where beef is slowly braised in red Burgundy wine and beef stock, adorned with pearl onions, mushrooms, and crisp bacon lardons.",
    image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&q=80",
    ingredients: [
      "3 lbs beef chuck, cut into 2-inch cubes",
      "6 slices thick-cut bacon, diced",
      "1 bottle dry red wine (Pinot Noir or Burgundy)",
      "2 cups beef stock",
      "2 tbsp tomato paste",
      "3 cloves garlic, minced",
      "1 bouquet garni (thyme, parsley, bay leaf)",
      "1 lb fresh mushrooms, quartered",
      "1 cup pearl onions, peeled",
      "2 tbsp flour",
      "2 tbsp butter",
      "Salt and pepper"
    ],
    instructions: [
      "In a large Dutch oven, fry the bacon until crisp. Remove bacon but leave the fat in the pot.",
      "Dry beef cubes, season with salt and pepper, and sear in the bacon fat in batches until well-browned. Remove and set aside.",
      "Stir flour into the fat, cooking for a minute. Add tomato paste and garlic.",
      "Pour in the wine and beef stock, scraping up the browned bits. Return beef and bacon to the pot along with the bouquet garni.",
      "Bring to a simmer, cover, and transfer to a 325°F (160°C) oven for 2.5 to 3 hours until beef is very tender.",
      "While beef is cooking, sauté mushrooms and pearl onions in butter until browned.",
      "During the last 15 minutes of stew cooking, stir in the mushrooms and pearl onions.",
      "Serve hot over mashed potatoes or egg noodles."
    ]
  },
  {
    id: 4,
    title: "Wagyu Ribeye with Garlic Herb Butter",
    slug: "wagyu-ribeye-garlic-butter",
    difficulty: "Easy",
    prepTime: "10 mins",
    cookTime: "10 mins",
    servings: 2,
    author: "Grill Master",
    rating: 5.0,
    reviewCount: 204,
    badge: "Premium",
    badgeColor: "bg-rose-500",
    description: "Sometimes the simplest preparation is best. This recipe lets the insanely marbled Wagyu beef shine, paired with a melting compound butter packed with fresh herbs.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&q=80",
    ingredients: [
      "2 Wagyu Ribeye steaks (about 1.5 inches thick)",
      "Coarse sea salt and freshly ground pepper",
      "1/2 cup unsalted butter, softened",
      "3 cloves garlic, minced",
      "1 tbsp fresh parsley, chopped",
      "1 tbsp fresh chives, chopped",
      "1 tsp fresh thyme leaves",
      "1 tbsp neutral oil (like canola)"
    ],
    instructions: [
      "Make the butter: Combine softened butter, garlic, parsley, chives, and thyme. Mash together, roll in parchment paper into a log, and chill.",
      "Take steaks out of the fridge 45 minutes before cooking to reach room temperature.",
      "Preheat a cast-iron skillet over high heat until it's smoking hot.",
      "Pat the steaks dry with paper towels and coat lightly with neutral oil. Season generously with course salt and pepper just before they hit the pan.",
      "Sear the steaks for 2-3 minutes per side for medium-rare, building a deep crust.",
      "Remove steaks from the pan and immediately top each with a thick slice of the garlic herb butter.",
      "Rest the steaks for 5-8 minutes before slicing."
    ]
  },
  {
    id: 5,
    title: "Smoked Texas-Style Beef Brisket",
    slug: "smoked-texas-beef-brisket",
    difficulty: "Hard",
    prepTime: "30 mins",
    cookTime: "12 hours",
    servings: 12,
    author: "Pitboss Pete",
    rating: 4.9,
    reviewCount: 421,
    badge: "BBQ Legend",
    badgeColor: "bg-orange-600",
    description: "The crown jewel of Texas barbecue. A whole packer brisket slowly smoked over post oak wood until it develops a dark, crusty bark and legendary jiggle.",
    image: "https://www.bradleysmoker.com/cdn/shop/articles/Smoky_sliced_beef_brisket_with_dark_crust_from_classic_Texas_smokehouse_266892525.jpg?v=1685570604",
    ingredients: [
      "1 whole packer beef brisket (12-14 lbs)",
      "1/2 cup coarse kosher salt",
      "1/2 cup coarse-ground black pepper",
      "Yellow mustard (as a binder)",
      "Apple cider vinegar or apple juice (for spritzing)"
    ],
    instructions: [
      "Trim the brisket: remove the thick hard fat ('deckle') and trim the fat cap down to an even 1/4 inch thickness across the top.",
      "Mix the salt and pepper perfectly 50/50. Mix well to create the 'Dalmatian rub'.",
      "Slather a very thin layer of mustard all over the brisket, then apply the rub generously and evenly.",
      "Preheat your smoker to 225°F-250°F (107°C-121°C). Use oak or hickory wood.",
      "Smoke the brisket fat-side up. After the first 3 hours, start spritzing dry spots with apple cider vinegar every hour.",
      "When the internal temperature reaches ~165°F (74°C) and the bark is well-formed, wrap the brisket tightly in pink butcher paper.",
      "Return to the smoker and cook until the internal temperature is between 200°F-205°F (93°C-96°C) and a probe slides in like soft butter.",
      "Rest the wrapped brisket in a dry cooler for at least 2 hours before slicing against the grain."
    ]
  },
  {
    id: 6,
    title: "Classic Smash Cheeseburgers",
    slug: "classic-smash-cheeseburgers",
    difficulty: "Easy",
    prepTime: "15 mins",
    cookTime: "10 mins",
    servings: 4,
    author: "Burger Bro",
    rating: 4.8,
    reviewCount: 633,
    badge: "Fast & Delicious",
    badgeColor: "bg-purple-500",
    description: "Thin, crispy-edged beef patties seared on a ripping hot griddle, blanketed in melted American cheese, and served on a toasted potato roll with special sauce.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    ingredients: [
      "1 lb Premium Ground Beef (80/20)",
      "4 potato buns, sliced and buttered",
      "4 slices American cheese",
      "Salt and pepper",
      "1/4 cup mayonnaise",
      "1 tbsp ketchup",
      "1 tbsp sweet pickle relish",
      "Shredded iceberg lettuce",
      "Sliced pickles"
    ],
    instructions: [
      "Make the special sauce: mix mayo, ketchup, and relish. Set aside.",
      "Divide the ground beef into 8 loosely packed balls (2 oz each). Do not compress them.",
      "Toast the buns in a dry skillet or griddle until golden brown, set aside.",
      "Heat a cast-iron skillet or griddle over medium-high heat until very hot.",
      "Place 2 beef balls on the griddle. Immediately smash them flat with a sturdy spatula (use parchment paper to prevent sticking).",
      "Season generously with salt and pepper. Cook undisturbed for 2 minutes until the edges are crispy and dark brown.",
      "Scrape firmly underneath to keep the crust, flip, and immediately add a slice of cheese to one patty.",
      "Stack the plain patty on top of the cheesy patty, let cook 1 more minute.",
      "Assemble: bun bottom, sauce, lettuce, double patty stack, pickles, bun top."
    ]
  },
  {
    id: 7,
    title: "Sticky BBQ Beef Short Ribs",
    slug: "sticky-bbq-beef-short-ribs",
    difficulty: "Medium",
    prepTime: "20 mins",
    cookTime: "3.5 hours",
    servings: 4,
    author: "Chef Mike",
    rating: 4.9,
    reviewCount: 288,
    badge: "Finger Lickin'",
    badgeColor: "bg-red-600",
    description: "Thick, meaty beef ribs braised in an Asian-inspired BBQ sauce until fall-off-the-bone tender, then roasted until sticky and caramelized.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    ingredients: [
      "4 lbs meaty beef short ribs",
      "1 cup beef broth",
      "1/2 cup soy sauce",
      "1/2 cup brown sugar",
      "1/4 cup hoisin sauce",
      "2 tbsp rice vinegar",
      "1 tbsp sesame oil",
      "4 cloves garlic, minced",
      "1 inch ginger, grated",
      "2 green onions, sliced",
      "Sesame seeds for garnish"
    ],
    instructions: [
      "Preheat oven to 325°F (160°C).",
      "Place short ribs in a large deep baking dish or Dutch oven.",
      "In a bowl, whisk together beef broth, soy sauce, brown sugar, hoisin, vinegar, sesame oil, garlic, and ginger.",
      "Pour the sauce over the ribs. Cover tightly with two layers of foil or a heavy lid.",
      "Braise in the oven for 3 hours, or until the meat is incredibly tender and pulling back from the bone.",
      "Remove ribs to a foil-lined baking sheet. Pour the braising liquid into a saucepan.",
      "Skim fat from the liquid, then boil it over medium-high heat for 10-15 minutes until reduced to a thick, sticky glaze.",
      "Brush ribs generously with the glaze and broil for 3-5 minutes until bubbling and caramelized.",
      "Garnish with green onions and sesame seeds."
    ]
  },
  {
    id: 8,
    title: "Classic Beef Stroganoff",
    slug: "classic-beef-stroganoff",
    difficulty: "Medium",
    prepTime: "20 mins",
    cookTime: "30 mins",
    servings: 4,
    author: "Elena's Kitchen",
    rating: 4.7,
    reviewCount: 410,
    badge: "Comfort",
    badgeColor: "bg-stone-500",
    description: "Tender strips of beef and earthy mushrooms swimming in a rich, tangy sour cream gravy, served affectionately over hot buttered egg noodles.",
    image: "https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=800&q=80",
    ingredients: [
      "1.5 lbs sirloin steak or tenderloin, sliced into thin strips",
      "1 lb cremini mushrooms, sliced",
      "1 medium onion, finely chopped",
      "2 cloves garlic, minced",
      "3 tbsp butter",
      "2 tbsp olive oil",
      "3 tbsp all-purpose flour",
      "2 cups beef broth",
      "1 tbsp Dijon mustard",
      "1 cup full-fat sour cream (at room temp)",
      "12 oz wide egg noodles",
      "Fresh parsley for garnish"
    ],
    instructions: [
      "Season beef strips with salt and pepper. Sear quickly over high heat in olive oil just until browned. Remove and set aside.",
      "In the same skillet, lower heat to medium, add butter, onions, and mushrooms. Sauté until onions are soft and mushrooms are browned.",
      "Add garlic and cook for 1 minute.",
      "Sprinkle flour over the vegetables, stir and cook for 1 minute.",
      "Gradually whisk in the beef broth and Dijon mustard. Bring to a simmer to thicken the sauce.",
      "Return beef (and any juices) to the skillet. Cook for 2 minutes to heat through.",
      "Remove from heat. Let it cool for a minute, then stir in the sour cream until completely smooth (do not boil after adding sour cream or it may curdle).",
      "Meanwhile, boil the egg noodles in salted water according to package directions. Drain and toss with a little butter.",
      "Serve the creamy beef mushroom mixture over the warm noodles. Garnish with chopped parsley."
    ]
  },
  {
    id: 9,
    title: "Pan-Seared Filet Mignon with Red Wine Pan Sauce",
    slug: "pan-seared-filet-mignon",
    difficulty: "Medium",
    prepTime: "15 mins",
    cookTime: "15 mins",
    servings: 2,
    author: "Steakhouse Secrets",
    rating: 4.9,
    reviewCount: 315,
    badge: "Date Night",
    badgeColor: "bg-rose-600",
    description: "The ultimate romantic dinner. Thick, tender filets seared to a perfect medium-rare, finished with a complex, glossy red wine reduction sauce.",
    image: "https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80",
    ingredients: [
      "2 Filet Mignon steaks (about 2 inches thick)",
      "Coarse salt and crushed black peppercorns",
      "2 tbsp neutral oil",
      "2 tbsp butter",
      "1 shallot, finely minced",
      "1/2 cup robust red wine (Cabernet Sauvignon)",
      "1/2 cup beef stock",
      "1 sprig fresh rosemary"
    ],
    instructions: [
      "Bring steaks to room temperature for 30 minutes. Generously season with salt and heavily press crushed pepper into both sides.",
      "Heat oil in a heavy stainless steel or cast-iron skillet over high heat.",
      "Sear the filets for 4-5 minutes per side for medium-rare. Remove to a plate and loosely tent with foil to rest.",
      "Reduce heat to medium. Add shallots to the pan drippings and sauté for 1 minute.",
      "Pour in the red wine to deglaze, scraping up the flavorful browned bits from the bottom.",
      "Add the beef stock and rosemary sprig. Simmer rapidly until the liquid is reduced by half and becomes syrupy.",
      "Remove pan from heat. Discard rosemary, and whisk in the butter until the sauce is glossy and slightly thickened.",
      "Spoon the red wine pan sauce over the rested steaks and serve immediately."
    ]
  },
  {
    id: 10,
    title: "Authentic Beef Pho (Phở Bò)",
    slug: "authentic-beef-pho",
    difficulty: "Hard",
    prepTime: "40 mins",
    cookTime: "8 hours",
    servings: 8,
    author: "Mama Nguyen",
    rating: 5.0,
    reviewCount: 520,
    badge: "Street Food",
    badgeColor: "bg-green-500",
    description: "Vietnam's most famous soup dish. The magic is in the deeply savory, spiced beef bone broth that simmers for hours, served with rice noodles and tender thin-sliced beef.",
    image: "https://farm8.staticflickr.com/7087/7174177733_6c0af1a0b2_b.jpg",
    ingredients: [
      "5 lbs beef bones (knuckles, marrow, leg)",
      "1 lb beef chuck or brisket (for cooking in broth)",
      "1 lb sirloin or eye of round, partially frozen (for raw slicing)",
      "2 large onions, halved",
      "1 large hand of ginger, halved longitudinally",
      "Spices: 5 star anise, 6 whole cloves, 1 cinnamon stick, 1 tbsp coriander seeds",
      "1/4 cup fish sauce",
      "2 tbsp rock sugar",
      "1 package flat rice noodles (Pho noodles)",
      "Garnish: bean sprouts, Thai basil, cilantro, lime wedges, hoisin, sriracha"
    ],
    instructions: [
      "Parboil bones: Place bones in a large pot, cover with water, boil for 10 minutes. Dump the water, rinse the bones and pot well. Return bones to pot with 6 quarts of fresh water.",
      "Char aromatics: Broil the ginger and onions until charred and fragrant. Peel off blackened skin, crush slightly, and add to the pot.",
      "Toast spices in a dry skillet until fragrant, tie them in a cheesecloth bag, and add to the pot.",
      "Add the beef chuck/brisket, fish sauce, and rock sugar to the pot. Simmer gently (do not boil) for at least 8 hours, skimming scum regularly.",
      "After 2 hours, remove the chuck/brisket, shock in cold water, and slice once cooled.",
      "Thinly slice the partially frozen sirloin against the grain into paper-thin pieces.",
      "Prepare noodles according to package instructions. Divide among large bowls.",
      "Top noodles with the cooked sliced beef and the raw thin sirloin slices.",
      "Strain the boiling hot broth, adjust seasoning with fish sauce if needed, and ladle directly over the raw beef to cook it in the bowl.",
      "Serve immediately with a plate of fresh garnishes and sauces on the side."
    ]
  }
];
